var N = null;var sourcesIndex = {};
sourcesIndex["either"] = {"name":"","files":["lib.rs"]};
sourcesIndex["hydroflow"] = {"name":"","dirs":[{"name":"lattice","files":["bottom.rs","dom_pair.rs","map_union.rs","mod.rs","null.rs","ord.rs","pair.rs","set_union.rs","top.rs"]},{"name":"op","files":["debug.rs","identity.rs","mod.rs","split_binary.rs","state_merge.rs"]}],"files":["collections.rs","eight_traits.rs","func.rs","graph.rs","hide.rs","lib.rs","tag.rs"]};
sourcesIndex["proc_macro2"] = {"name":"","files":["detection.rs","fallback.rs","lib.rs","marker.rs","parse.rs","wrapper.rs"]};
sourcesIndex["quote"] = {"name":"","files":["ext.rs","format.rs","ident_fragment.rs","lib.rs","runtime.rs","spanned.rs","to_tokens.rs"]};
sourcesIndex["ref_cast"] = {"name":"","files":["layout.rs","lib.rs","trivial.rs"]};
sourcesIndex["ref_cast_impl"] = {"name":"","files":["lib.rs"]};
sourcesIndex["serde"] = {"name":"","dirs":[{"name":"de","files":["ignored_any.rs","impls.rs","mod.rs","seed.rs","utf8.rs","value.rs"]},{"name":"private","files":["de.rs","doc.rs","mod.rs","ser.rs","size_hint.rs"]},{"name":"ser","files":["fmt.rs","impls.rs","impossible.rs","mod.rs"]}],"files":["integer128.rs","lib.rs","macros.rs"]};
sourcesIndex["static_assertions"] = {"name":"","files":["assert_cfg.rs","assert_eq_align.rs","assert_eq_size.rs","assert_fields.rs","assert_impl.rs","assert_obj_safe.rs","assert_trait.rs","assert_type.rs","const_assert.rs","lib.rs"]};
sourcesIndex["static_rc"] = {"name":"","files":["lib.rs","rc.rs","rcref.rs","utils.rs"]};
sourcesIndex["std_collection_traits"] = {"name":"","files":["allocator.rs","associated.rs","capacity.rs","elem.rs","exact_size.rs","iter.rs","lib.rs","misc.rs","sequential.rs"]};
sourcesIndex["syn"] = {"name":"","dirs":[{"name":"gen","files":["clone.rs","gen_helper.rs"]}],"files":["attr.rs","await.rs","bigint.rs","buffer.rs","custom_keyword.rs","custom_punctuation.rs","data.rs","derive.rs","discouraged.rs","error.rs","export.rs","expr.rs","ext.rs","generics.rs","group.rs","ident.rs","lib.rs","lifetime.rs","lit.rs","lookahead.rs","mac.rs","macros.rs","op.rs","parse.rs","parse_macro_input.rs","parse_quote.rs","path.rs","print.rs","punctuated.rs","sealed.rs","span.rs","spanned.rs","thread.rs","token.rs","ty.rs","verbatim.rs"]};
sourcesIndex["unicode_xid"] = {"name":"","files":["lib.rs","tables.rs"]};
createSourceSidebar();
